### ISSUE TITLE
请问大佬为什么不把扩展提交给微软？

### ISSUE THREAD

**Issue by mendax1234** [gauseen/faster-hosts#7]
请问大佬为什么不把扩展提交给微软？我用的是Edge浏览器，每次打开的时候都显示扩展建议关闭，非常麻烦，大佬能不能讲扩展提交给Microsoft，这样就方便了

**Comment by ghost** [comment]
进商店是要入场费的应该.

**Comment by mendax1234** [comment]
啊这，是这样的吗，微软也更苹果一样？

**Comment by ghost** [comment]
@mendax1234 谷歌浏览器的扩展商店最便宜, 5刀, 一次性收费. 做成免费会变成国内公交免费的寿星卡啥的, 你上班的时候连个座位都没有.

**Comment by mendax1234** [comment]
啊这，确实
